version: '3.8'

services:
  webrtc-detection:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8765:8765"
    volumes:
      - ./models:/app/models:ro
      - ./public/onnx-wasm:/app/public/onnx-wasm:ro
      - ./.env.local:/app/.env.local:ro
    environment:
      - NODE_ENV=production
      - MODE=${MODE:-wasm}
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - webrtc-network

networks:
  webrtc-network:
    driver: bridge